---
title: "ST558 Porject 1"
author: "Chien-Lan Hsueh"
institute: Online Statistics Master Program, NCSU
date: "`r Sys.Date()`"
output:
  html_notebook:
    theme: cerulean
    highlight: haddock
    code_folding: none
---

```{r include=FALSE}
if (!require("pacman")) utils::install.packages("pacman", dependencies = TRUE)

pacman::p_load(
	here, keyring,
	stats, 
	tidyverse, rlang,
	magrittr,
	glue, scales,
	naniar,
	httr, jsonlite
)
```


## Setup
```{r}
# Uncomment the following line to save the API key
#rstudioapi::askForSecret("OMDb")
```

## Test - By Title
```{r}
# use API to send out a query
mv_data <- 
  GET(
    url = "http://www.omdbapi.com/", 
    query = list(
      t = "Guardians of the Galaxy Vol. 2",
      #t = "Batman",
      apiKey = key_get("RStudio Keyring Secrets", "OMDb"))
  )

# print the message: if the http status is successful
print(glue("Is the http status successfull? {mv_data$status_code %>% between(200, 299)}"))

# take a look of the response and check status_code 
str(mv_data, max.level = 1)

# parse the JSON data
parsed <- fromJSON(rawToChar(mv_data$content))

# names of parsed data
names(parsed)
```

```{r}
# columns that need to be converted to appropriate data types
## numeric columns
col_num <- c(2, 5, 16:18, 22)
## datetime columns
col_date <- c(4, 21)

# save the source, author and title columns into a data frame
df_mv <- parsed %>%
  as_tibble() %>% 
  mutate(across(col_num, parse_number)) %>% 
  mutate(across(col_date, ~ parse_date(.x, format = "%d %b %Y")))
str(df_mv)
```


## Test - By Search
```{r}
# use API to send out a query
mv_data2 <- 
  GET(
    url = "http://www.omdbapi.com/", 
    query = list(
      s = "Batman",
      apiKey = key_get("RStudio Keyring Secrets", "OMDb"))
  )

# print the message: if the http status is successful
print(glue("Is the http status successfull? {mv_data$status_code %>% between(200, 299)}"))

# take a look of the response and check status_code 
str(mv_data2, max.level = 1)

# parse the JSON data
parsed2 <- fromJSON(rawToChar(mv_data2$content))

# names of parsed data
names(parsed2)
```

```{r}
parsed2$totalResults
parsed2$Response
```


```{r}
# columns that need to be converted to appropriate data types
## numeric columns
col_num <- c(2, 5, 16:18, 22)
## datetime columns
col_date <- c(4, 21)

# save the source, author and title columns into a data frame
df_mv2 <- parsed2$Search %>%
  as_tibble() %>% 
  arrange(Type, Year) %>% 
  mutate(Year = parse_number(Year))
str(df_mv2)
```

## Helper functions

```{r}




OMDb_movie <- function(by = c("id", "title", "search"), value, page, ...) {
  
  # save all arguments as a named list
  args <- as.list(match.call())[-1]
  
  # verify query method argument `by` to be one of the supported methods
  by <- match.arg(by)
  
  # assign default query value if it's missing in argument
  if(is_missing(value)){
    value <- c("tt1285016", "Batman", "Batman")[by == c("id", "title", "search")]
  }

  # assign default page value (only needed when using search method)
  if(!is_missing(page) && by == "search") {
    args$page <- as.character(page)
  }
    
  # remove `by` and `value` from the list
  # also remove argument `r` (if exists) because this function only supports JSON
  args[c("by", "value", "r")] <- NULL

  # construct the query as a list of query parameters and the api key
  query = 
    # key-value pair from the query method `by` and query value `value`
    switch(by,
      id = list(i = value),
      title = list(t = value),
      search = list(s = value)) %>% 
    # append the rest of query parameters
    append(args) %>% 
    # add the api key
    append(list(apiKey = key_get("RStudio Keyring Secrets", "OMDb")))
  
  print(query)
  
  # send API query request
  rawdata <- GET(url = "http://www.omdbapi.com/", query = query)

  # check if the request is successful
  # if not, stop and print the HTTP status code
  if(!between(rawdata$status_code, 200, 299)) {
    stop(glue("The query request is not successful (HTTP status code: {rawdata$status_code})!"))
  }

  # parse the JSON content data
  parsed <- fromJSON(rawToChar(rawdata$content))

  # convert parsed data into a data frame based on query method
  if (by == "search"){
    # search returns a list of movies
    df <- parsed$Search %>% 
      as_tibble() %>% 
      mutate(Year = parse_number(Year), totalResults = parsed$totalResults)
    
    totalPages <- ceiling(as.numeric(parsed$totalResults)/10)
    print(glue("totalResults: {parsed$totalResults}, totalPages: {totalPages}"))
    #print(glue("{names(query)}"))
    
    if (!("page" %in% names(query)) && totalPages > 1){
      for (i in 2:totalPages) {
        #print(glue("range: {2:totalPages}, {by} - {value}: {i}"))
        df <- bind_rows(df, OMDb_movie(by, value, page = i))
      }
    }
    
    #df <- df %>% arrange(Type, Year)
    
  } else {
    # search by id and title returns info of the movie
    print("id or title")
    # convert the data into appropriate data type and save in a data frame
    df <- parsed %>% 
      as_tibble() %>% 
      # convert columns to numeric type
      mutate(across(matches(
        c("Year", "Runtime", "Metascore", "imdbRating", "imdbVotes", "BoxOffice", "totalSeasons")),
        ~parse_number(.x, na = c("", "NA", "N/A")))) %>% 
      # convert columns to datetime type
      mutate(across(matches(
        c("Released", "DVD")), 
        ~parse_date(.x, na = c("", "NA", "N/A"), format = "%d %b %Y")))
  }
  
  return(df)
}
```


```{r}
x1 <- OMDb_movie(by = "id", value = "tt0078346") # movie
x2 <- OMDb_movie(by = "id", value = "tt0106057") # series
x3 <- OMDb_movie(by = "id", value = "tt0772202") # game
```
```{r}
names(x1)
names(x2)
names(x3)

str(x1)
```



```{r}
x <- OMDb_movie()
x <- OMDb_movie(by = "id")
x <- OMDb_movie(by = "id", value = "tt3896198")
x <- OMDb_movie(by = "id", value = "tt0044231")
x <- OMDb_movie(by = "title")
x <- OMDb_movie(by = "title", value = "Guardians of the Galaxy Vol. 2")
x <- OMDb_movie(by = "search", value = "Batman")
x <- OMDb_movie(by = "search", value = "Batman", y = 2022)


y <- OMDb_movie(by = "search", value = "Guardians of the Galaxy")
y1 <- OMDb_movie(by = "search", value = "Guardians of the Galaxy", page = 1)
y2 <- OMDb_movie(by = "search", value = "Guardians of the Galaxy", page = 2)



y3 <- OMDb_movie(by = "search", value = "Superman", page = 3)
y4 <- OMDb_movie(by = "search", value = "Superman", page = 4)
y5 <- OMDb_movie(by = "search", value = "Superman", page = 5)
y15 <- OMDb_movie(by = "search", value = "Superman", page = 15)
y_2021 <- OMDb_movie(by = "search", value = "Superman", y = 2021)
y_2015 <- OMDb_movie(by = "search", value = "Superman", y = 2015)
y_2010 <- OMDb_movie(by = "search", value = "Superman", y = 2010)


x <- OMDb_movie(by = "idx")
```

